version: '3.8'

services:
  military-hardware-detection:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: military-hardware-detection-api
    ports:
      - "8000:8000"
    volumes:
      - ./swagger-ui:/app/swagger-ui  # Mount the Swagger UI folder to ensure offline docs are served
    environment:
      - PYTHONUNBUFFERED=1  # Ensures real-time log output
    restart: always  # Ensures the container restarts automatically in case of a failure

