names:
- Artilary
- Missile
- Radar
- M. Rocket Launcher
- Soldier
- Tank
- Vehicle
nc: 7
test: /home/nic/workspace/Mlops/MHD_1/KIIT-MiTA/test/images
train: /home/nic/workspace/Mlops/MHD_1/KIIT-MiTA/train/images
val: /home/nic/workspace/Mlops/MHD_1/KIIT-MiTA/valid/images
